// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type League struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	Country string `json:"country"`
	Tier    int    `json:"tier"`
}

type NewLeague struct {
	Name    string `json:"name"`
	Country string `json:"country"`
	Tier    int    `json:"tier"`
}

type NewPlayer struct {
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Height      float64 `json:"height"`
	Nationality string  `json:"nationality"`
	Position    string  `json:"position"`
	TeamID      int     `json:"teamId"`
	Number      int     `json:"number"`
	Foot        string  `json:"foot"`
}

type NewTeam struct {
	Name         string `json:"name"`
	LeagueID     int    `json:"leagueId"`
	FoundingYear int    `json:"foundingYear"`
}

type Player struct {
	ID          int     `json:"id"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Height      float64 `json:"height"`
	Nationality string  `json:"nationality"`
	Position    string  `json:"position"`
	Team        *Team   `json:"team"`
	Number      int     `json:"number"`
	Foot        string  `json:"foot"`
}

type Team struct {
	ID           int     `json:"id"`
	League       *League `json:"league"`
	Name         string  `json:"name"`
	FoundingYear int     `json:"foundingYear"`
}
